### PR TITLE
fix trace id propagation in client

### PR DESCRIPTION
**Pull request by Widar91**
Follows discussion on Gitter: https://gitter.im/kamon-io/Kamon?at=5ace0ddf6bbe1d2739d5f0ab

### CODE REVIEW

**Comment by dpsoft** [comment]
Hey @Widar91 , please remember to sign the [CLA](https://docs.google.com/forms/d/e/1FAIpQLSdhLT5zYRzdzRKRybFJcXUUuhpdJzRiiDhPZKtCTgToQaqpGw/viewform) to merge this PR :) Thanks a lot

**Comment by dpsoft** [comment]
@aggenebbisj and @ptrlaszlo have any comments!

**Comment by ptrlaszlo** [comment]
@Widar91 nice solution!

**Comment by aggenebbisj** [comment]
Agree on that. Nice indeed!

**Comment by dpsoft** [comment]
@Widar91 thanks for proposing this PR!

**Comment by dpsoft** [comment]
I'll make a release asap!

**Comment by ivantopo** [comment]
Thanks a lot @Widar91 :smiley:

**Pull request merged**
