### PR TITLE
Return B3 headers in server response

### PR DESCRIPTION
**Pull request by ptrlaszlo**

### CODE REVIEW

**Comment by dpsoft** [comment]
@ptrlaszlo sorry for the late response, I will make a release in a couple of hours.

**Comment by ptrlaszlo** [comment]
Thank you!

**Comment by ivantopo** [comment]
Hey @ptrlaszlo, just wanted to mention one little thing for the future: in Kamon 2.0 we are not writing the entire context in the response but rather specifically copying the trace and span ids into the response, and the header names for those are configurable but default to non-B3 names!

When you guys upgrade, please take that into account :)

**Comment by ptrlaszlo** [comment]
Thanks for the heads-up!

**Comment by ptrlaszlo** [comment]
I can't see the latest version on https://mvnrepository.com/artifact/io.kamon/kamon-http4s, do you know by any chance when does it get uploaded?

**Comment by dpsoft** [comment]
@ptrlaszlo done!. I was sure I had made the release  :anguished: ... I've published the artifact to maven too.

https://bintray.com/kamon-io/releases/kamon-http4s/1.0.13

**Comment by ptrlaszlo** [comment]
Thank you 🙏

**Pull request merged**
