### PR TITLE
Upgrade http4s to 0.19.0-M1

### PR DESCRIPTION
**Pull request by Widar91**
This also upgrades scala version to 2.12.6 because of this: https://github.com/scala/bug/issues/10800

### CODE REVIEW

**Comment by Widar91** [comment]
Tests seem to fail unpredictably, sometimes they pass, other times not. This happens both on my machine and seemingly on travis, but unfortunately I don't have permission to restart the build

**Comment by dpsoft** [comment]
@Widar91 thanks for proposing this PR!

**Comment by Widar91** [comment]
@dpsoft Thanks for merging =) would it be possible for you to release a snapshot version of this such that I can already start using it in my project?

**Comment by dpsoft** [comment]
@Widar91 https://github.com/kamon-io/kamon-http4s/releases/tag/v1.0.9.

**Comment by Widar91** [comment]
Thank you!

**Pull request merged**
