### PR TITLE
Server status code as metric tag

### PR DESCRIPTION
**Pull request by ptrlaszlo**
Add server status code as metric tag if `Http4s.addHttpStatusCodeAsMetricTag` is set

### CODE REVIEW

**Comment by dpsoft** [comment]
Hey @ptrlaszlo  , please remember to sign the [CLA](https://docs.google.com/forms/d/e/1FAIpQLSdhLT5zYRzdzRKRybFJcXUUuhpdJzRiiDhPZKtCTgToQaqpGw/viewform) to merge this PR :) Thanks a lot

**Comment by ivantopo** [comment]
@dpsoft he already signed it because of other PR on the kamon-akka-http module :)

**Comment by ptrlaszlo** [comment]
@dpsoft I already did for a different

**Comment by dpsoft** [comment]
Hey @ptrlaszlo thanks a lot for the contribution!!!

**Pull request merged**
