### PR TITLE
Update dependencies to most recent versions

### PR DESCRIPTION
**Pull request by jchapuis**
- Merge #50
- Update kamon to 2.6.1
- Update http4s dependencies to latest (0.22.15, 0.23.19, 1.0.0-M38)

### CODE REVIEW

**Comment by jchapuis** [comment]
@ivantopo this branch works for us 🥳

**Comment by ivantopo** [comment]
Hey @jchapuis and @vaslabs, I looked around the PR and there is a ton of http4s-specific stuff that I couldn't follow, but I'm going to blindly trust you and merge this. Publishing should come soon after :pray:

**Comment by vaslabs** [comment]
> Hey @jchapuis and @vaslabs, I looked around the PR and there is a ton of http4s-specific stuff that I couldn't follow, but I'm going to blindly trust you and merge this. Publishing should come soon after pray

thanks, will test and follow-up with any fixes anyway :D

**Comment by ivantopo** [comment]
Hey guys, I wanted to push a release for this and noticed that 1.0.x versions of http4s dropped support for Scala 2.12 at `1.0.0-M31` (see https://github.com/http4s/http4s/releases/tag/v1.0.0-M31)

My guess is that the 1.x version should only be published for Scala 2.13 and 3.x so I'll try to make that happen :)

**Pull request merged**
