### PR TITLE
Support scala 2.13

### PR DESCRIPTION
**Pull request by rlebran**
- Cross compile scala 2.12 / 2.13 (drop scala 2.11 support)
- Bump http4s version to 0.21.0-M5
- Bump sbt version to 1.3.2

### CODE REVIEW

**Comment by bplommer** [comment]
It would be great if this could be released as a milestone 😄

**Comment by khrupalyk** [comment]
Hi there! Any plans to merge this PR?

**Comment by dpsoft** [comment]
@rlebran sorry for the late response. Thanks for proposing this PR.

**Comment by khrupalyk** [comment]
Hi @dpsoft. Mabe you know when we can see the new version of kamon on maven?

**Comment by dpsoft** [comment]
@khrupalyk done https://github.com/kamon-io/kamon-http4s/releases/tag/v2.0.1 in the way to maven central

**Pull request merged**
