### PR TITLE
Refactor into a multi-module project

### PR DESCRIPTION
**Pull request by hygt**
This is basically #44 #45 and #46 together.

The README probably needs a deeper overhaul.

### CODE REVIEW

**Review by dpsoft — APPROVED** [review]
@hygt awesome!!! @ivantopo WDYT?

**Comment by ivantopo** [comment]
Seems fine to me as well, although, to be honest, I'm not super familiar with this. I'm going to trust you guys on this and proceed to merge and release this thing :smile:

**Comment by PawelJ-PL** [comment]
Hi @ivantopo. Is it possible to release it?

**Comment by dpsoft** [comment]
> Hi @ivantopo. Is it possible to release it?

done!

**Pull request merged**
